package br.com.vidaconecta.notification.api;

public enum NotificationType {
	APPOINTMENT_SCHEDULED,
	APPOINTMENT_CONFIRMED,
	APPOINTMENT_CANCELLED,
	APPOINTMENT_COMPLETED,
	PRESCRIPTION_ISSUED,
	CONSENT_GRANTED,
	CONSENT_REVOKED,
	EHR_NOTE_ADDED
}
